# Generated by Django 3.2.25 on 2025-09-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportedIdsMap",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                ("connection", models.CharField(db_index=True, max_length=100)),
                ("foreign_id", models.BigIntegerField()),
                ("local_id", models.BigIntegerField()),
            ],
            options={
                "unique_together": {("connection", "model_name", "foreign_id")},
            },
        ),
    ]
